/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


import Vistas.FrmCorresp_Salida;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
    /**
     * @author Johana Serrano, Erika Tique, Giovani...
     */
public class FrmCorresp_Salida extends javax.swing.JFrame {
    public FrmCorresp_Salida() {
        initComponents();
        AsignarFecha();
        this.jTextNumRadS.setEditable(false);
    }
    
         private void AsignarFecha(){
            Calendar fecha = new GregorianCalendar();
            String hoy = "";
            int año = fecha.get(Calendar.YEAR);
            int mes = fecha.get(Calendar.MONTH)+1;
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
            int hora = fecha.get(Calendar.HOUR_OF_DAY);
            int minuto = fecha.get(Calendar.MINUTE);
            int segundo = fecha.get(Calendar.SECOND);
            hoy = dia+"/"+mes+"/"+año+" "+hora+":"+minuto+":"+segundo; 
             
             try{   
                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                    Date fechaDate = new Date();
                    fechaDate = formato.parse(hoy);              
                                                          
                    this.jDateFchaE.setDate(fechaDate);
                    jDateFchaE.getDateEditor().setEnabled(false);
                    this.jDateFchaElab.setDate(fechaDate);
                    jDateFchaElab.getDateEditor().setEnabled(false);
                   
                    
                 
             }catch (ParseException ex){
             Logger.getLogger(FrmCorresp_Salida.class.getName()).log(Level.SEVERE,null, ex);
         }
             
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCombTipoD = new javax.swing.JComboBox();
        jLFchaEnv = new javax.swing.JLabel();
        jCombRadicadoEnt = new javax.swing.JComboBox();
        jLDoc = new javax.swing.JLabel();
        jLNumRadE = new javax.swing.JLabel();
        jLNumRadS = new javax.swing.JLabel();
        jLRta = new javax.swing.JLabel();
        jLFchaElab = new javax.swing.JLabel();
        jTextFuncionarioD = new javax.swing.JTextField();
        jLFuncionarioD = new javax.swing.JLabel();
        jLAsunto = new javax.swing.JLabel();
        jLDoc_Envio = new javax.swing.JLabel();
        jDateFchaE = new com.toedter.calendar.JDateChooser();
        jTextDependenciaD = new javax.swing.JTextField();
        jLMensajero = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRta = new javax.swing.JTextArea();
        jLDependenciaD = new javax.swing.JLabel();
        jDateFchaElab = new com.toedter.calendar.JDateChooser();
        jTextDuc = new javax.swing.JTextField();
        jTextNumRadS = new javax.swing.JTextField();
        jBSalida = new javax.swing.JButton();
        jLDoc1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableUsuarios = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDocEnvio = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAsunto = new javax.swing.JTextArea();
        jCombmensajero = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Correspodencia Salida");

        jLFchaEnv.setText("Fecha Envio:");

        jCombRadicadoEnt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el Radicado Entrada" }));

        jLDoc.setText("Número Documento:");

        jLNumRadE.setText("Numero de Radicado Entrada:");

        jLNumRadS.setText("Numero de Radicado Salida:");

        jLRta.setText("Respuesta:");

        jLFchaElab.setText("Fecha Elaboracion:");

        jTextFuncionarioD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFuncionarioDFocusLost(evt);
            }
        });
        jTextFuncionarioD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFuncionarioDKeyTyped(evt);
            }
        });

        jLFuncionarioD.setText("Funcionario Destinatario:");

        jLAsunto.setText("Asunto:");

        jLDoc_Envio.setText("Documento Envio:");

        jDateFchaE.setDateFormatString("dd/MM/yyyy HH:mm:ss");
        jDateFchaE.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateFchaEPropertyChange(evt);
            }
        });

        jTextDependenciaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDependenciaDActionPerformed(evt);
            }
        });
        jTextDependenciaD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDependenciaDFocusLost(evt);
            }
        });
        jTextDependenciaD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDependenciaDKeyTyped(evt);
            }
        });

        jLMensajero.setText("Mensajero:");

        jTextAreaRta.setColumns(20);
        jTextAreaRta.setRows(5);
        jTextAreaRta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaRtaFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaRta);

        jLDependenciaD.setText("Dependencia Destinatario:");

        jDateFchaElab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDateFchaElabFocusLost(evt);
            }
        });
        jDateFchaElab.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateFchaElabPropertyChange(evt);
            }
        });

        jTextDuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDucActionPerformed(evt);
            }
        });
        jTextDuc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDucFocusLost(evt);
            }
        });
        jTextDuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDucKeyTyped(evt);
            }
        });

        jTextNumRadS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumRadSActionPerformed(evt);
            }
        });
        jTextNumRadS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNumRadSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNumRadSFocusLost(evt);
            }
        });

        jBSalida.setText("SALIDA");
        jBSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalidaActionPerformed(evt);
            }
        });

        jLDoc1.setText("Tipo de Documento");

        TableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TableUsuarios);

        jTextAreaDocEnvio.setColumns(20);
        jTextAreaDocEnvio.setRows(5);
        jTextAreaDocEnvio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaDocEnvioFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaDocEnvio);

        jTextAreaAsunto.setColumns(20);
        jTextAreaAsunto.setRows(5);
        jTextAreaAsunto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaAsuntoFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jTextAreaAsunto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLMensajero, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCombmensajero, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLFuncionarioD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLRta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLNumRadE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLNumRadS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFchaEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLDependenciaD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLDoc_Envio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateFchaE, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLFchaElab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateFchaElab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jTextFuncionarioD)
                            .addComponent(jTextDependenciaD)
                            .addComponent(jScrollPane1)
                            .addComponent(jCombTipoD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextDuc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextNumRadS, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCombRadicadoEnt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumRadE)
                    .addComponent(jCombRadicadoEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumRadS)
                    .addComponent(jTextNumRadS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDoc)
                    .addComponent(jTextDuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLDoc1)
                        .addGap(19, 19, 19)
                        .addComponent(jLFchaEnv))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCombTipoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFchaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFchaElab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFchaElab, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFuncionarioD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFuncionarioD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDependenciaD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDependenciaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLDoc_Envio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMensajero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombmensajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDependenciaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDependenciaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDependenciaDActionPerformed

    private void jTextDependenciaDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDependenciaDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDependenciaDKeyTyped

    private void jTextDucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDucActionPerformed

    private void jTextDucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDucKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(caracter < '0' || caracter > '9'){
            evt.consume();
        }
        String Cadena = jTextDuc.getText();
        if (Cadena.length() >= 11) {
            evt.consume();
            int Long = this.jTextDuc.getText().length();
            if (Long <= 11){
                JOptionPane.showMessageDialog(null, "Erro solo puede ingresar Once digitos","Error",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTextDucKeyTyped

    private void jBSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalidaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBSalidaActionPerformed

    private void jTextFuncionarioDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFuncionarioDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFuncionarioDKeyTyped

    private void jTextNumRadSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNumRadSFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextNumRadSFocusLost

    private void jTextDucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDucFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDucFocusLost

    private void jTextAreaRtaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaRtaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaRtaFocusLost

    private void jTextAreaDocEnvioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaDocEnvioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaDocEnvioFocusLost

    private void jTextFuncionarioDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFuncionarioDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFuncionarioDFocusLost

    private void jTextDependenciaDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDependenciaDFocusLost
        // TODO add your handling code here:
          int Long = this.jTextDependenciaD.getText().length();
        if(Long < 1) {
            JOptionPane.showMessageDialog(null, "Este campo es Obligatorio...!", "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextDependenciaDFocusLost

    private void jTextNumRadSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumRadSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumRadSActionPerformed

    private void jTextNumRadSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNumRadSFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextNumRadSFocusGained

    private void jDateFchaElabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateFchaElabFocusLost
        // TODO add your handling code here:
        Date Fecha1, Fecha2;

        Fecha1 =this.jDateFchaE.getDate();
        Fecha2 =this.jDateFchaElab.getDate();

        if (Fecha2.after(Fecha1)){
	JOptionPane.showMessageDialog(null, "La Fecha de elaboración no debe ser posterior a la de envio!! ");
	this.jDateFchaE.setDate(null);
	this.jDateFchaE.requestFocus();
}      
    }//GEN-LAST:event_jDateFchaElabFocusLost

    private void jTextAreaAsuntoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaAsuntoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAsuntoFocusLost

    private void jDateFchaEPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateFchaEPropertyChange
        // TODO add your handling code here:
        ((JTextField)this.jDateFchaE.getDateEditor().getUiComponent()).setEditable(false);
    }//GEN-LAST:event_jDateFchaEPropertyChange

    private void jDateFchaElabPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateFchaElabPropertyChange
        // TODO add your handling code here:
        ((JTextField)this.jDateFchaElab.getDateEditor().getUiComponent()).setEditable(false);
    }//GEN-LAST:event_jDateFchaElabPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCorresp_Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCorresp_Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCorresp_Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCorresp_Salida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCorresp_Salida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TableUsuarios;
    public javax.swing.JButton jBSalida;
    public javax.swing.JComboBox jCombRadicadoEnt;
    public javax.swing.JComboBox jCombTipoD;
    public javax.swing.JComboBox jCombmensajero;
    public com.toedter.calendar.JDateChooser jDateFchaE;
    public com.toedter.calendar.JDateChooser jDateFchaElab;
    public javax.swing.JLabel jLAsunto;
    public javax.swing.JLabel jLDependenciaD;
    public javax.swing.JLabel jLDoc;
    public javax.swing.JLabel jLDoc1;
    public javax.swing.JLabel jLDoc_Envio;
    public javax.swing.JLabel jLFchaElab;
    public javax.swing.JLabel jLFchaEnv;
    public javax.swing.JLabel jLFuncionarioD;
    public javax.swing.JLabel jLMensajero;
    public javax.swing.JLabel jLNumRadE;
    public javax.swing.JLabel jLNumRadS;
    public javax.swing.JLabel jLRta;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextArea jTextAreaAsunto;
    public javax.swing.JTextArea jTextAreaDocEnvio;
    public javax.swing.JTextArea jTextAreaRta;
    public javax.swing.JTextField jTextDependenciaD;
    public javax.swing.JTextField jTextDuc;
    public javax.swing.JTextField jTextFuncionarioD;
    public javax.swing.JTextField jTextNumRadS;
    // End of variables declaration//GEN-END:variables

    private SimpleDateFormat SimpleDateFormat(String ddMMyyyy) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
